language: node_js

sudo: false

matrix:
    include:
        - env: PROJECT=packages/lib

branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_install:
- npm update

install:
- npm install

script:
- npm test
- npm install codecov -g & codecov
- if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then echo "$PROJECT is being built"; else echo "$PROJECT is NOT being built"; fi

after_success:
  - codecov --token=:3eda0bdf-2301-4bad-8fcf-0ec45b6e61fa
